### ISSUE TITLE
Text to update is incorrect when push to server

### ISSUE THREAD

**Issue by wH1t3-l0tUs** [wH1t3-l0tUs/SE-Project#8]

**Comment by kembo13520** [comment]
there is some problem with the function handle the method

`       private void SendEditText(String id, String text) {`
`        JSONObject jsonObject = new JSONObject();`
`        try {`
`            jsonObject.put("text", text);`
`        } catch (JSONException e) {`
`            e.printStackTrace();`
`        }`
